[2024-05-24T07:35:01.427+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MySQL_to_Redshift_v2.mysql_to_s3_nps scheduled__2024-05-22T09:00:00+00:00 [queued]>
[2024-05-24T07:35:01.431+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MySQL_to_Redshift_v2.mysql_to_s3_nps scheduled__2024-05-22T09:00:00+00:00 [queued]>
[2024-05-24T07:35:01.431+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-05-24T07:35:01.437+0000] {taskinstance.py:1382} INFO - Executing <Task(SqlToS3Operator): mysql_to_s3_nps> on 2024-05-22 09:00:00+00:00
[2024-05-24T07:35:01.439+0000] {standard_task_runner.py:57} INFO - Started process 159 to run task
[2024-05-24T07:35:01.441+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'MySQL_to_Redshift_v2', 'mysql_to_s3_nps', 'scheduled__2024-05-22T09:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/MySQL_to_Redshift_v2.py', '--cfg-path', '/tmp/tmpfvqqk7_8']
[2024-05-24T07:35:01.442+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask mysql_to_s3_nps
[2024-05-24T07:35:01.464+0000] {task_command.py:416} INFO - Running <TaskInstance: MySQL_to_Redshift_v2.mysql_to_s3_nps scheduled__2024-05-22T09:00:00+00:00 [running]> on host d579a67aea10
[2024-05-24T07:35:01.484+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-24T07:35:01.498+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='MySQL_to_Redshift_v2' AIRFLOW_CTX_TASK_ID='mysql_to_s3_nps' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-22T09:00:00+00:00'
[2024-05-24T07:35:01.506+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/sql_to_s3.py", line 176, in execute
    sql_hook = self._get_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/sql_to_s3.py", line 206, in _get_hook
    conn = BaseHook.get_connection(self.sql_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_conn_id` isn't defined
[2024-05-24T07:35:01.508+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=MySQL_to_Redshift_v2, task_id=mysql_to_s3_nps, execution_date=20240522T090000, start_date=20240524T073501, end_date=20240524T073501
[2024-05-24T07:35:01.513+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task mysql_to_s3_nps (The conn_id `mysql_conn_id` isn't defined; 159)
[2024-05-24T07:35:01.541+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-05-24T07:35:01.552+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
